### ISSUE TITLE
Import crashes when more than 10 input columns are included

### ISSUE THREAD

**Issue by EisBaller** [pinussilvestrus/camunda-modeler-excel-import-plugin#45]
Hi,
when we import a file with more than 10 input columns, the import breaks with an error message.
We used the Camunda modeler with version 4.6 and 4.7, but always got the same result.

We used the following file for testing:
[Import_13.xlsx](https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/files/6391826/Import_13.xlsx)

The following error message was displayed:
[diagram_2.dmn] unparsable content <inputEntry> detected
	line: 525
	column: 8
	nested error: duplicate ID <InputEntry110> [ warning ]
[diagram_2.dmn] unparsable content <inputEntry> detected
	line: 945
	column: 8
	nested error: duplicate ID <InputEntry210> [ warning ]
[diagram_2.dmn] unparsable content <inputEntry> detected
	line: 1365
	column: 8
	nested error: duplicate ID <InputEntry310> [ warning ]
[diagram_2.dmn] number of cells is not equal to number of cols
    at e.value (webpack:///node_modules/table-js/lib/core/Sheet.js:81:14)
    at addRow (webpack:///node_modules/dmn-js-decision-table/lib/import/TableImporter.js:79:26)
    at add (webpack:///node_modules/dmn-js-decision-table/lib/import/Importer.js:30:24)
    at element (webpack:///node_modules/dmn-js-decision-table/lib/import/TableTreeWalker.js:12:19)
    at file:///C:/Users/EisBaller/Documents/Camunda/Camunda%20Modeler%204.7/resources/app.asar/public/8.8.js:8:218156
    at iterator (webpack:///node_modules/min-dash/dist/index.esm.js:145:15)
    at rules (webpack:///node_modules/dmn-js-decision-table/lib/import/TableTreeWalker.js:54:12)
    at file:///C:/Users/EisBaller/Documents/Camunda/Camunda%20Modeler%204.7/resources/app.asar/public/8.8.js:8:261126
    at file:///C:/Users/EisBaller/Documents/Camunda/Camunda%20Modeler%204.7/resources/app.asar/public/8.8.js:8:261144
    at this (webpack:///node_modules/dmn-js-decision-table/lib/Viewer.js:88:30)
    at open (webpack:///node_modules/dmn-js-shared/lib/base/Manager.js:531:25)
    at _switchView (webpack:///node_modules/dmn-js-shared/lib/base/Manager.js:373:11)
    at file:///C:/Users/EisBaller/Documents/Camunda/Camunda%20Modeler%204.7/resources/app.asar/public/8.8.js:8:647716
    at file:///C:/Users/EisBaller/Documents/Camunda/Camunda%20Modeler%204.7/resources/app.asar/public/8.8.js:8:621137
    at apply (webpack:///node_modules/@sentry/browser/esm/helpers.js:71:22) [ error ]
This error may be the result of a plug-in compatibility issue. [ info ]
Disable plug-ins (restarts the app) [ info ]

**Comment by pinussilvestrus** [comment]
Thanks for reporting!
Seems like there are problems when auto-generating the ID of the rule entries

```
[diagram_1.dmn] unparsable content <inputEntry> detected
	line: 529
	column: 8
	nested error: duplicate ID <InputEntry110> [ warning ]
```

Will have a look :)

**Comment by pinussilvestrus** [comment]
Hi @EisBaller,

I implemented a fix (https://github.com/pinussilvestrus/camunda-modeler-excel-import-plugin/commit/09907f1729cab1193c8a6827e92cff209b4895c4) to ensure entries can't have duplicated ids. That should make the import of your Excel Sheet work.

Can you maybe double-check with the latest state on `main`?

**Comment by EisBaller** [comment]
Now it works fine!
Thank you very much @pinussilvestrus!
